### ISSUE TITLE
Card won't respond to finger swipe

### ISSUE THREAD

**Issue by Gyoko** [gmetekorkmaz/SwipeStack#1]
Items will remain unresponsive to swipes with fingers unless **visibleCount** is equal to number of children in **swipeStack**.

Thanks for the widget, by the way!

**Comment by gmetekorkmaz** [comment]
are you sure?

**Comment by Gyoko** [comment]
Yes. I tested with the code you provided in **Usage** section and cards can be dragged only when visibleCount == items.length.

**Comment by gmetekorkmaz** [comment]
Send pr.

**Comment by Gyoko** [comment]
pr?

**Comment by gmetekorkmaz** [comment]
pull request

**Comment by Gyoko** [comment]
Just copy-paste the file to test it

**Comment by letmebelazy** [comment]
Well, if you wrap the card by widgets like GestureDetector, and use properties related to drag, its swipe seems to get stuck.
