### ISSUE TITLE
How to listen to  left/right swipe

### ISSUE THREAD

**Issue by Fethi1** [gmetekorkmaz/SwipeStack#9]

**Comment by ahmedmehanna** [comment]
I think you can use
`onSwipe: (int index, SwiperPosition position) `
and from `position` you can detect the dirction

**Comment by Fethi1** [comment]
there was no value in position that says it is on left or right

**Comment by ahmedmehanna** [comment]
I implemented this package on my code
Can you submit a sample of your code here and I will try to help you?

**Comment by Fethi1** [comment]
i removed that part, sorry!
can you please provide the code for this:
`onSwipe: (int index, SwiperPosition position){
if(LEFT)
.....
if(RIGHT)
}
`
i just need the values for LEFT and RIGHT conditions

**Comment by ahmedmehanna** [comment]
you can find enum inside the package
`enum SwiperPosition { None, Left, Right }`
So you can check the value of `position` by
```
onSwipe: (int index, SwiperPosition position){ 
     if(position == SwiperPosition.Left){

     }
     if(position == SwiperPosition.Right){

     } 
}
```

**Comment by Fethi1** [comment]
ok Thank you so much
